### PR TITLE
Changes in model now reflect on form: Issue #82 & Issue #23

### PR DESCRIPTION
**Pull request by xcskier56**
Changes by @BenjaminHorn and @michetti to allow updates in the model to be reflected in the form. This should close Issue #82 and Issue #23

### CODE REVIEW

**Comment by joshpfosi** [comment]
@asaf, will this be merged soon? I am debating forking from this branch as this change is make or break.

**Comment by koryteg** [comment]
+1 for this. will this be merged soon?

**Comment by xcskier56** [comment]
@joshpfosi Have you created a fork for this feature? I'd be happy to help.

**Comment by shearwaterintl** [comment]
I actually have not. I don't have time at the moment, but it should be straightforward to take this pull request, right?

**Comment by joshpfosi** [comment]
I actually have not. I don't have time at the moment, but it should be straightforward to take this pull request, right?

**Comment by koryteg** [comment]
@joshpfosi for myself I just set my package.json to get this fork and commit for the time being, until this gets updated. I should probably fork @xcskier56 so I am not depending on his fork.

**Comment by joshpfosi** [comment]
Any progress on this? Cans someone list their package.json? How can I pull in `http://github.com/perk-health/ember-forms.git` into my project? Thanks!

**Comment by asaf** [comment]
Merged.

**Comment by joshpfosi** [comment]
I still experience this problem even with EmberForms 0.6.0. Looking into this now, but it appears to be the identical problem.

**Comment by pedrokiefer** [comment]
@joshpfosi I'm not sure if this is not already fixed on this fork: https://github.com/piceaTech/ember-rapid-forms

**Comment by joshpfosi** [comment]
@pedrokiefer, I experience an issue when using ember-rapid-forms:

```
version: 0.1.15
Cannot find module 'handlebars'
Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/joshpfosi/shearwater/ember/bower_components/ember/ember-template-compiler.js:34:16
    at Object.<anonymous> (/Users/joshpfosi/shearwater/ember/bower_components/ember/ember-template-compiler.js:332:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```
Any ideas on this?

**Comment by joshpfosi** [comment]
Hmm. Just created a fresh ember app and experienced the same issue: https://github.com/joshpfosi/ember-rapid-forms-bug

Do you have a working `package.json` I could check against?

**Comment by pedrokiefer** [comment]
@joshpfosi I think it's something with the version of your ember-cli, but I might be mistaken.

**Pull request closed without merging**
